### ISSUE TITLE
Missing cowsay.scif

### ISSUE THREAD

**Issue by dkp** [containers-ftw/apps#30]
Hi, 
I'm trying to learn using docker and following the examples, but https://github.com/sci-f/sci-f.github.io/blob/master/_posts/tutorials/cowsay.scif is missing.

**Comment by vsoch** [comment]
Can you show me what you are reading that needs that file?

**Comment by dkp** [comment]
https://sci-f.github.io/apps/examples/tutorials/getting-started


Container Modularity

The next goal is container modularity! For this example, we are going to switch to a more fun build recipe - cowsay! If you want to grab the recipe to follow along, you can get it here. Let’s again build a Docker and Singularity container.<https://github.com/sci-f/sci-f.github.io/blob/master/_posts/tutorials/cowsay.scif>

(get it here gives me 404)
________________________________

**Comment by vsoch** [comment]
Ah, sorry about that! It was the right path, but just for the wrong repo. I've fixed it in the getting-started doc that you linked, and the file is here:

https://github.com/sci-f/apps/blob/master/_posts/tutorials/cowsay.scif

**Comment by dkp** [comment]
Thanks so much!  You are fast!

**Comment by vsoch** [comment]
Hehe, np :)

**Comment by dkp** [comment]
Although I can list the apps after this and display the help, they complain when I try to run them:
0057:feckless:working/cowsay_scif> docker run vanessa/cowsay run fortune
/scif/apps/fortune/scif/runscript: line 3: /usr/games/fortune: No such file or directory
[fortune] executing /bin/bash /scif/apps/fortune/scif/runscript

There was a complaint during the build: e.g., 
E: Unable to locate package fortune (see below)

10056:feckless:working/cowsay_scif> docker build -f Dockerfile.cowsay -t vanessa/cowsay .
Sending build context to Docker daemon  3.584kB
Step 1/3 : FROM vanessa/scif
latest: Pulling from vanessa/scif
05d1a5232b46: Already exists
d974dd5eb235: Already exists
2de22c73730e: Already exists
444f639f1b28: Already exists
c1b600cb48ba: Already exists
b495641f397a: Already exists
65a68ca010c9: Already exists
c4376e4875ad: Already exists
Digest: sha256:0e2b284c6f649c1f1c28fa01edef32aee6b46564a895cd917fd29de50279476d
Status: Downloaded newer image for vanessa/scif:latest
 ---> 906f11929ebc
Step 2/3 : ADD cowsay.scif /
 ---> 938ec617a5f0
Step 3/3 : RUN scif install /cowsay.scif
 ---> Running in 8b15b006ed6b
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package fortune
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cowsay
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package lolcat
Installing base at /scif
+ apprun     fortune
+ appenv     fortune
+ apphelp     fortune
+ appinstall fortune
+ apprun     cowsay
+ appenv     cowsay
+ apphelp     cowsay
+ appinstall cowsay
+ apprun     lolcat
+ appenv     lolcat
+ apphelp     lolcat
+ appinstall lolcat
Removing intermediate container 8b15b006ed6b
 ---> 730d01638649
Successfully built 730d01638649
Successfully tagged vanessa/cowsay:latest

**Comment by vsoch** [comment]
Oh no! I wonder if they removed it from package repos?

I can't test this now, but I'll take a look in about 90 minutes.

**Comment by dkp** [comment]
Good, that gives me time to figure out if I did something stupid ; )

**Comment by vsoch** [comment]
Ah! Actually a quick glance this is an easy fix-  we need to do apt-get update. I have a meeting in 3 minutes but I can push a fixed file before that! One second...

**Comment by vsoch** [comment]
okay try the updated cowsay.scif now.

**Comment by dkp** [comment]
That is looking pretty good! lolcat doesn't seem to do much, but the others are clearly functional.  Thanks again! 

10096:feckless:working/cowsay_scif> docker run vanessa/cowsay apps
   fortune
    cowsay
    lolcat

10097:feckless:working/cowsay_scif> docker run vanessa/cowsay help fortune
    fortune is the best app

10098:feckless:working/cowsay_scif> docker run vanessa/cowsay run fortune
[fortune] executing /bin/bash /scif/apps/fortune/scif/runscript
For courage mounteth with occasion.
		-- William Shakespeare, "King John"

10099:feckless:working/cowsay_scif> docker run vanessa/cowsay run cowsay
[cowsay] executing /bin/bash /scif/apps/cowsay/scif/runscript

 __
<  >
 --
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
10100:feckless:working/cowsay_scif> docker run vanessa/cowsay run lolcat

[lolcat] executing /bin/bash /scif/apps/lolcat/scif/runscript

**Comment by vsoch** [comment]
lolcat is a bit weird - you actually pipe stuff into it, so here is the default cowsay:

```
$ docker run  vanessa/cowsay run cowsay HELLO MY NAME IS MR COW

 _________________________
< HELLO MY NAME IS MR COW >
 -------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
For lolcat, the usage is actually to pipe some text *into* it to make it colorful, so the app in the container should be something like:

```bash
echo "$@" | /usr/games/lolcat
```

Or it could be combined with fortune:

```
exec /usr/games/fortune | /usr/games/lolcat
```
I just updated the lolcat entrypoint to handle this, and also added a "unicorn" app that will pipe fortune into lolcow, but since Docker doesn't readily show color, it doesn't do much. But if you get to install and run lolcat on your local machine, you can enjoy the beautiful colors (or Google it online to see what it looks like).

**Comment by dkp** [comment]
Ah, I wondered where the colors were.  Singularity shows them, right?
I think this SCIF tool is a fantastic idea.  I'm surprised I don't see more about it, especially with the proliferation of BIDS containers that are sometimes similar and/or overlapping.

I still have more to absorb, but I'll get there.  I really appreciate your time.

**Comment by vsoch** [comment]
Yes, with Singularity you will see them!

> I still have more to absorb, but I'll get there. I really appreciate your time.

Definitely! Please ping me if you ever need / want any help. The scif here is intended for researchers (python == language of scientific programming) but if you are interested, there is also a golang client https://github.com/sci-f/scif-go. There hasn't been as much uptake as I would have anticipated, but I also haven't spent a large amount of time proving to people that it's useful. I'm also terrible at asking scientific questions. So if you want any kind of help, and have a use case in mind, you know where I am :L)
